# Generated by Django 5.2.9 on 2026-02-02 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoilIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp1', models.DateTimeField(auto_now_add=True)),
                ('timestamp2', models.DateField(auto_now=True)),
                ('lot', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('thickness', models.CharField(blank=True, max_length=255, null=True)),
                ('width', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('Type0', models.CharField(blank=True, max_length=255, null=True)),
                ('Type1', models.CharField(blank=True, max_length=255, null=True)),
                ('Type2', models.CharField(blank=True, max_length=255, null=True)),
                ('thickness', models.CharField(blank=True, max_length=255, null=True, verbose_name='หนา')),
                ('width', models.CharField(blank=True, max_length=255, null=True, verbose_name='กว้าง')),
                ('length', models.CharField(blank=True, max_length=255, null=True, verbose_name='ยาว')),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
                ('note1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Note1 ขอบ กับ HRC')),
                ('note2', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoilPallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, unique=True)),
                ('coilin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coil.coilin')),
                ('type0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coil.sku')),
            ],
        ),
        migrations.CreateModel(
            name='CoilNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, unique=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('coilpallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coil.coilpallet')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('thickness', models.CharField(blank=True, max_length=255, null=True)),
                ('width', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp1', models.DateField(blank=True, null=True)),
                ('coilin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coil.coilin')),
            ],
        ),
        migrations.CreateModel(
            name='NW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nw_kg', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coil.label')),
            ],
        ),
        migrations.AddField(
            model_name='coilin',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coil.owner'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='coilin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coil.profile'),
        ),
        migrations.AddField(
            model_name='sku',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coil.supplier'),
        ),
        migrations.AddField(
            model_name='coilin',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coil.supplier'),
        ),
    ]
