# Generated by Django 5.2.9 on 2026-02-02 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coilin',
            name='thickness',
        ),
        migrations.RemoveField(
            model_name='coilin',
            name='width',
        ),
    ]
