# Generated by Django 5.2.9 on 2026-02-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coil', '0002_remove_coilin_thickness_remove_coilin_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coilin',
            name='lot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
