# Generated by Django 5.2.10 on 2026-02-03 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coil', '0003_alter_coilin_lot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoilOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp1', models.DateTimeField(blank=True, null=True)),
                ('timestamp2', models.DateField(auto_now=True)),
                ('full_coil_partial', models.CharField(blank=True, max_length=255, null=True, verbose_name='เต็มม้วน/บางส่วน')),
                ('coil_kg', models.FloatField(blank=True, null=True, verbose_name='Coil-Kg')),
                ('type0', models.CharField(blank=True, max_length=255, null=True)),
                ('job_number', models.CharField(blank=True, max_length=255, null=True)),
                ('job_name_short', models.CharField(blank=True, max_length=255, null=True)),
                ('job_qty', models.CharField(blank=True, max_length=255, null=True)),
                ('department_cutting', models.CharField(blank=True, max_length=255, null=True, verbose_name='แผนกที่ตัด')),
                ('note_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Note-1')),
                ('coil_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coil.coilnumber')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coil.sku')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coil.profile')),
            ],
        ),
    ]
