# Generated by Django 5.2.9 on 2026-02-03 01:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coil', '0004_coilout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coilout',
            name='timestamp1',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
