# Generated by Django 5.2.9 on 2026-02-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coil', '0005_alter_coilout_timestamp1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coilout',
            name='timestamp1',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
