# Generated by Django 5.2.10 on 2026-02-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coil', '0006_alter_coilout_timestamp1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coilout',
            name='timestamp1',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
