# Generated by Django 5.2.10 on 2026-02-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coil', '0008_alter_coilout_timestamp1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coilin',
            name='timestamp1',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
