# Generated by Django 5.2.8 on 2026-02-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coil", "0009_alter_coilin_timestamp1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coilnumber",
            name="number",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="coilnumber",
            unique_together={("coilpallet", "number")},
        ),
    ]
