# Generated by Django 5.1.5 on 2026-02-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coil", "0010_alter_coilnumber_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sku",
            name="note",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="หมายเหตุ"
            ),
        ),
        migrations.AlterField(
            model_name="sku",
            name="Type0",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="sku",
            name="Type1",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="sku",
            name="Type2",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="sku",
            name="color",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="sku",
            name="grade",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="sku",
            name="length",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="ยาว"
            ),
        ),
        migrations.AlterField(
            model_name="sku",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="sku",
            name="note1",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Note1 ขอบ กับ HRC"
            ),
        ),
        migrations.AlterField(
            model_name="sku",
            name="note2",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="sku",
            name="thickness",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="หนา"
            ),
        ),
        migrations.AlterField(
            model_name="sku",
            name="width",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="กว้าง"
            ),
        ),
        migrations.AddConstraint(
            model_name="sku",
            constraint=models.UniqueConstraint(
                fields=(
                    "name",
                    "Type0",
                    "Type1",
                    "Type2",
                    "thickness",
                    "width",
                    "length",
                    "color",
                    "grade",
                    "manufacturer",
                    "note",
                    "note1",
                    "note2",
                ),
                name="unique_sku_combination",
            ),
        ),
    ]
