# Generated by Django 5.1.5 on 2026-02-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coil", "0011_sku_note_alter_sku_type0_alter_sku_type1_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sku",
            name="unique_sku_combination",
        ),
        migrations.RemoveField(
            model_name="sku",
            name="name",
        ),
        migrations.AddConstraint(
            model_name="sku",
            constraint=models.UniqueConstraint(
                fields=(
                    "Type0",
                    "Type1",
                    "Type2",
                    "thickness",
                    "width",
                    "length",
                    "color",
                    "grade",
                    "manufacturer",
                    "note",
                    "note1",
                    "note2",
                ),
                name="unique_sku_combination",
            ),
        ),
    ]
