# Generated by Django 5.1.5 on 2026-02-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coil", "0012_remove_sku_unique_sku_combination_remove_sku_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sku",
            name="Type0",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="sku",
            name="Type1",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="sku",
            name="color",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="sku",
            name="grade",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="sku",
            name="length",
            field=models.CharField(default="", max_length=255, verbose_name="ยาว"),
        ),
        migrations.AlterField(
            model_name="sku",
            name="note1",
            field=models.CharField(
                default="", max_length=255, verbose_name="Note1 ขอบ กับ HRC"
            ),
        ),
        migrations.AlterField(
            model_name="sku",
            name="thickness",
            field=models.CharField(default="", max_length=255, verbose_name="หนา"),
        ),
        migrations.AlterField(
            model_name="sku",
            name="width",
            field=models.CharField(default="", max_length=255, verbose_name="กว้าง"),
        ),
    ]
