# Generated by Django 5.1.5 on 2026-02-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coil", "0013_alter_sku_type0_alter_sku_type1_alter_sku_color_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sku",
            name="unique_sku_combination",
        ),
        migrations.RemoveField(
            model_name="sku",
            name="note",
        ),
        migrations.AlterField(
            model_name="sku",
            name="note2",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="หมายเหตุ"
            ),
        ),
        migrations.AddConstraint(
            model_name="sku",
            constraint=models.UniqueConstraint(
                fields=(
                    "Type0",
                    "Type1",
                    "Type2",
                    "thickness",
                    "width",
                    "length",
                    "color",
                    "grade",
                    "manufacturer",
                    "note1",
                    "note2",
                ),
                name="unique_sku_combination",
            ),
        ),
    ]
