# Generated by Django 5.1.5 on 2026-02-16 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coil", "0014_remove_sku_unique_sku_combination_remove_sku_note_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_job", models.DateField(blank=True, null=True)),
                ("job_number", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "job_name_short",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("job_qty", models.CharField(blank=True, max_length=255, null=True)),
                ("job_duefin", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "job_note_job",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_note_process",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_note_packing",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_process_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_process_1_duefin",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_process_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_process_2_duefin",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_process_3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_process_3_duefin",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_process_4",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_process_4_duefin",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_process_5",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_process_6",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_process_7",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_process_8",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_process_9",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_process_10",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_process_11",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_process_12",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_process_13",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_process_14",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_process_15",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_process_16",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_process_17",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_process_18",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_process_19",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_process_20",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="coilout",
            name="job_name_short",
        ),
        migrations.RemoveField(
            model_name="coilout",
            name="job_number",
        ),
        migrations.RemoveField(
            model_name="coilout",
            name="job_qty",
        ),
        migrations.AddField(
            model_name="coilout",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="coil.job",
            ),
        ),
    ]
