# Generated by Django 5.1.5 on 2026-02-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coil", "0017_complete_department_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_process_10_duefin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="job_process_11_duefin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="job_process_12_duefin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="job_process_13_duefin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="job_process_14_duefin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="job_process_15_duefin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="job_process_16_duefin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="job_process_17_duefin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="job_process_18_duefin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="job_process_19_duefin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="job_process_20_duefin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="job_process_5_duefin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="job_process_6_duefin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="job_process_7_duefin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="job_process_8_duefin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="job_process_9_duefin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_duefin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_process_1_duefin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_process_2_duefin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_process_3_duefin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_process_4_duefin",
            field=models.DateField(blank=True, null=True),
        ),
    ]
